module.exports = {
  campus_results: [{
    campus_id: 1,
    name: "서울",
    web_address: null,
    building_rseults: [{
      building_id: 2,
      campus_id: 1,
      name: "남부학습센터"
    }, {
      building_id: 1,
      campus_id: 1,
      name: "서울지역대학"
    }, {
      building_id: 6,
      campus_id: 1,
      name: "남양주시학습관"
    }, {
      building_id: 5,
      campus_id: 1,
      name: "동두천시학습관"
    }, {
      building_id: 3,
      campus_id: 1,
      name: "북부학습센터"
    }, {
      building_id: 4,
      campus_id: 1,
      name: "서부학습센터"
    }]
  }, {
    campus_id: 2,
    name: "경기",
    web_address: null,
    building_rseults: [{
      building_id: 7,
      campus_id: 2,
      name: "경기지역대학"
    }, {
      building_id: 8,
      campus_id: 2,
      name: "성남시학습관"
    }, {
      building_id: 9,
      campus_id: 2,
      name: "안산시학습관"
    }, {
      building_id: 10,
      campus_id: 2,
      name: "안양시학습관"
    }]
  }, {
    campus_id: 3,
    name: "인천",
    web_address: null,
    building_rseults: [{
      building_id: 11,
      campus_id: 3,
      name: "인천지역대학"
    }, {
      building_id: 12,
      campus_id: 3,
      name: "부천시학습관"
    }]
  }, {
    campus_id: 4,
    name: "강원",
    web_address: null,
    building_rseults: [{
      building_id: 14,
      campus_id: 4,
      name: "속초시학습관"
    }, {
      building_id: 18,
      campus_id: 4,
      name: "원주시학습관"
    }, {
      building_id: 17,
      campus_id: 4,
      name: "태백시학습관"
    }, {
      building_id: 16,
      campus_id: 4,
      name: "동해시학습관"
    }, {
      building_id: 15,
      campus_id: 4,
      name: "강릉시학습관"
    }, {
      building_id: 13,
      campus_id: 4,
      name: "강원지역대학(춘천시)"
    }]
  }, {
    campus_id: 5,
    name: "충북",
    web_address: null,
    building_rseults: [{
      building_id: 19,
      campus_id: 5,
      name: "충북지역대학"
    }, {
      building_id: 20,
      campus_id: 5,
      name: "제천시학습관"
    }, {
      building_id: 21,
      campus_id: 5,
      name: "충주시학습관"
    }]
  }, {
    campus_id: 6,
    name: "대전·충남",
    web_address: null,
    building_rseults: [{
      building_id: 26,
      campus_id: 6,
      name: "서산시학습관"
    }, {
      building_id: 25,
      campus_id: 6,
      name: "홍선군학습관"
    }, {
      building_id: 23,
      campus_id: 6,
      name: "천안시학습관"
    }, {
      building_id: 22,
      campus_id: 6,
      name: "대전-충남지역대학"
    }, {
      building_id: 24,
      campus_id: 6,
      name: "공주시학습관"
    }]
  }, {
    campus_id: 7,
    name: "대구·경북",
    web_address: null,
    building_rseults: [{
      building_id: 27,
      campus_id: 7,
      name: "대구-경북지역대학"
    }, {
      building_id: 28,
      campus_id: 7,
      name: "포항시학습관"
    }, {
      building_id: 29,
      campus_id: 7,
      name: "경주시학습관"
    }, {
      building_id: 30,
      campus_id: 7,
      name: "구미시학습관"
    }, {
      building_id: 31,
      campus_id: 7,
      name: "상주시학습관"
    }, {
      building_id: 32,
      campus_id: 7,
      name: "안동시학습관"
    }]
  }, {
    campus_id: 8,
    name: "부산·울산·경남",
    web_address: null,
    building_rseults: [{
      building_id: 37,
      campus_id: 8,
      name: "창원시학습관"
    }, {
      building_id: 38,
      campus_id: 8,
      name: "거제시학습관"
    }, {
      building_id: 36,
      campus_id: 8,
      name: "창원시학습관 진해별관"
    }, {
      building_id: 35,
      campus_id: 8,
      name: "경남지역대학"
    }, {
      building_id: 34,
      campus_id: 8,
      name: "울산지역대학"
    }, {
      building_id: 33,
      campus_id: 8,
      name: "부산지역대학"
    }]
  }, {
    campus_id: 9,
    name: "전북",
    web_address: null,
    building_rseults: [{
      building_id: 39,
      campus_id: 9,
      name: "전북지역대학"
    }, {
      building_id: 40,
      campus_id: 9,
      name: "남원시학습관"
    }, {
      building_id: 41,
      campus_id: 9,
      name: "정읍시학습관"
    }, {
      building_id: 42,
      campus_id: 9,
      name: "익산시학습관"
    }, {
      building_id: 43,
      campus_id: 9,
      name: "군산시학습관"
    }]
  }, {
    campus_id: 10,
    name: "광주·전남",
    web_address: null,
    building_rseults: [{
      building_id: 44,
      campus_id: 10,
      name: "광주-전남지역대학"
    }, {
      building_id: 45,
      campus_id: 10,
      name: "순천시학습관"
    }, {
      building_id: 46,
      campus_id: 10,
      name: "여수시학습관"
    }, {
      building_id: 47,
      campus_id: 10,
      name: "해남군학습관"
    }, {
      building_id: 48,
      campus_id: 10,
      name: "목포시학습관"
    }]
  }, {
    campus_id: 11,
    name: "제주",
    web_address: null,
    building_rseults: [{
      building_id: 49,
      campus_id: 11,
      name: "제주지역대학"
    }]
  }],
  building_results: [{
    building_id: 2,
    campus_id: 1,
    name: "남부학습센터"
  }, {
    building_id: 1,
    campus_id: 1,
    name: "서울지역대학"
  }, {
    building_id: 6,
    campus_id: 1,
    name: "남양주시학습관"
  }, {
    building_id: 5,
    campus_id: 1,
    name: "동두천시학습관"
  }, {
    building_id: 3,
    campus_id: 1,
    name: "북부학습센터"
  }, {
    building_id: 4,
    campus_id: 1,
    name: "서부학습센터"
  }, {
    building_id: 7,
    campus_id: 2,
    name: "경기지역대학"
  }, {
    building_id: 8,
    campus_id: 2,
    name: "성남시학습관"
  }, {
    building_id: 9,
    campus_id: 2,
    name: "안산시학습관"
  }, {
    building_id: 10,
    campus_id: 2,
    name: "안양시학습관"
  }, {
    building_id: 11,
    campus_id: 3,
    name: "인천지역대학"
  }, {
    building_id: 12,
    campus_id: 3,
    name: "부천시학습관"
  }, {
    building_id: 14,
    campus_id: 4,
    name: "속초시학습관"
  }, {
    building_id: 18,
    campus_id: 4,
    name: "원주시학습관"
  }, {
    building_id: 17,
    campus_id: 4,
    name: "태백시학습관"
  }, {
    building_id: 16,
    campus_id: 4,
    name: "동해시학습관"
  }, {
    building_id: 15,
    campus_id: 4,
    name: "강릉시학습관"
  }, {
    building_id: 13,
    campus_id: 4,
    name: "강원지역대학(춘천시)"
  }, {
    building_id: 19,
    campus_id: 5,
    name: "충북지역대학"
  }, {
    building_id: 20,
    campus_id: 5,
    name: "제천시학습관"
  }, {
    building_id: 21,
    campus_id: 5,
    name: "충주시학습관"
  }, {
    building_id: 26,
    campus_id: 6,
    name: "서산시학습관"
  }, {
    building_id: 25,
    campus_id: 6,
    name: "홍선군학습관"
  }, {
    building_id: 23,
    campus_id: 6,
    name: "천안시학습관"
  }, {
    building_id: 22,
    campus_id: 6,
    name: "대전-충남지역대학"
  }, {
    building_id: 24,
    campus_id: 6,
    name: "공주시학습관"
  }, {
    building_id: 27,
    campus_id: 7,
    name: "대구-경북지역대학"
  }, {
    building_id: 28,
    campus_id: 7,
    name: "포항시학습관"
  }, {
    building_id: 29,
    campus_id: 7,
    name: "경주시학습관"
  }, {
    building_id: 30,
    campus_id: 7,
    name: "구미시학습관"
  }, {
    building_id: 31,
    campus_id: 7,
    name: "상주시학습관"
  }, {
    building_id: 32,
    campus_id: 7,
    name: "안동시학습관"
  }, {
    building_id: 37,
    campus_id: 8,
    name: "창원시학습관"
  }, {
    building_id: 38,
    campus_id: 8,
    name: "거제시학습관"
  }, {
    building_id: 36,
    campus_id: 8,
    name: "창원시학습관 진해별관"
  }, {
    building_id: 35,
    campus_id: 8,
    name: "경남지역대학"
  }, {
    building_id: 34,
    campus_id: 8,
    name: "울산지역대학"
  }, {
    building_id: 33,
    campus_id: 8,
    name: "부산지역대학"
  }, {
    building_id: 39,
    campus_id: 9,
    name: "전북지역대학"
  }, {
    building_id: 40,
    campus_id: 9,
    name: "남원시학습관"
  }, {
    building_id: 41,
    campus_id: 9,
    name: "정읍시학습관"
  }, {
    building_id: 42,
    campus_id: 9,
    name: "익산시학습관"
  }, {
    building_id: 43,
    campus_id: 9,
    name: "군산시학습관"
  }, {
    building_id: 44,
    campus_id: 10,
    name: "광주-전남지역대학"
  }, {
    building_id: 45,
    campus_id: 10,
    name: "순천시학습관"
  }, {
    building_id: 46,
    campus_id: 10,
    name: "여수시학습관"
  }, {
    building_id: 47,
    campus_id: 10,
    name: "해남군학습관"
  }, {
    building_id: 48,
    campus_id: 10,
    name: "목포시학습관"
  }, {
    building_id: 49,
    campus_id: 11,
    name: "제주지역대학"
  }],
  campuses: [{
    campus_id: 1,
    name: "서울",
    web_address: null,
    building_rseults: [{
      building_id: 2,
      campus_id: 1,
      name: "남부학습센터"
    }, {
      building_id: 1,
      campus_id: 1,
      name: "서울지역대학"
    }, {
      building_id: 6,
      campus_id: 1,
      name: "남양주시학습관"
    }, {
      building_id: 5,
      campus_id: 1,
      name: "동두천시학습관"
    }, {
      building_id: 3,
      campus_id: 1,
      name: "북부학습센터"
    }, {
      building_id: 4,
      campus_id: 1,
      name: "서부학습센터"
    }]
  }, {
    campus_id: 2,
    name: "경기",
    web_address: null,
    building_rseults: [{
      building_id: 7,
      campus_id: 2,
      name: "경기지역대학"
    }, {
      building_id: 8,
      campus_id: 2,
      name: "성남시학습관"
    }, {
      building_id: 9,
      campus_id: 2,
      name: "안산시학습관"
    }, {
      building_id: 10,
      campus_id: 2,
      name: "안양시학습관"
    }]
  }, {
    campus_id: 3,
    name: "인천",
    web_address: null,
    building_rseults: [{
      building_id: 11,
      campus_id: 3,
      name: "인천지역대학"
    }, {
      building_id: 12,
      campus_id: 3,
      name: "부천시학습관"
    }]
  }, {
    campus_id: 4,
    name: "강원",
    web_address: null,
    building_rseults: [{
      building_id: 14,
      campus_id: 4,
      name: "속초시학습관"
    }, {
      building_id: 18,
      campus_id: 4,
      name: "원주시학습관"
    }, {
      building_id: 17,
      campus_id: 4,
      name: "태백시학습관"
    }, {
      building_id: 16,
      campus_id: 4,
      name: "동해시학습관"
    }, {
      building_id: 15,
      campus_id: 4,
      name: "강릉시학습관"
    }, {
      building_id: 13,
      campus_id: 4,
      name: "강원지역대학(춘천시)"
    }]
  }, {
    campus_id: 5,
    name: "충북",
    web_address: null,
    building_rseults: [{
      building_id: 19,
      campus_id: 5,
      name: "충북지역대학"
    }, {
      building_id: 20,
      campus_id: 5,
      name: "제천시학습관"
    }, {
      building_id: 21,
      campus_id: 5,
      name: "충주시학습관"
    }]
  }, {
    campus_id: 6,
    name: "대전·충남",
    web_address: null,
    building_rseults: [{
      building_id: 26,
      campus_id: 6,
      name: "서산시학습관"
    }, {
      building_id: 25,
      campus_id: 6,
      name: "홍선군학습관"
    }, {
      building_id: 23,
      campus_id: 6,
      name: "천안시학습관"
    }, {
      building_id: 22,
      campus_id: 6,
      name: "대전-충남지역대학"
    }, {
      building_id: 24,
      campus_id: 6,
      name: "공주시학습관"
    }]
  }, {
    campus_id: 7,
    name: "대구·경북",
    web_address: null,
    building_rseults: [{
      building_id: 27,
      campus_id: 7,
      name: "대구-경북지역대학"
    }, {
      building_id: 28,
      campus_id: 7,
      name: "포항시학습관"
    }, {
      building_id: 29,
      campus_id: 7,
      name: "경주시학습관"
    }, {
      building_id: 30,
      campus_id: 7,
      name: "구미시학습관"
    }, {
      building_id: 31,
      campus_id: 7,
      name: "상주시학습관"
    }, {
      building_id: 32,
      campus_id: 7,
      name: "안동시학습관"
    }]
  }, {
    campus_id: 8,
    name: "부산·울산·경남",
    web_address: null,
    building_rseults: [{
      building_id: 37,
      campus_id: 8,
      name: "창원시학습관"
    }, {
      building_id: 38,
      campus_id: 8,
      name: "거제시학습관"
    }, {
      building_id: 36,
      campus_id: 8,
      name: "창원시학습관 진해별관"
    }, {
      building_id: 35,
      campus_id: 8,
      name: "경남지역대학"
    }, {
      building_id: 34,
      campus_id: 8,
      name: "울산지역대학"
    }, {
      building_id: 33,
      campus_id: 8,
      name: "부산지역대학"
    }]
  }, {
    campus_id: 9,
    name: "전북",
    web_address: null,
    building_rseults: [{
      building_id: 39,
      campus_id: 9,
      name: "전북지역대학"
    }, {
      building_id: 40,
      campus_id: 9,
      name: "남원시학습관"
    }, {
      building_id: 41,
      campus_id: 9,
      name: "정읍시학습관"
    }, {
      building_id: 42,
      campus_id: 9,
      name: "익산시학습관"
    }, {
      building_id: 43,
      campus_id: 9,
      name: "군산시학습관"
    }]
  }, {
    campus_id: 10,
    name: "광주·전남",
    web_address: null,
    building_rseults: [{
      building_id: 44,
      campus_id: 10,
      name: "광주-전남지역대학"
    }, {
      building_id: 45,
      campus_id: 10,
      name: "순천시학습관"
    }, {
      building_id: 46,
      campus_id: 10,
      name: "여수시학습관"
    }, {
      building_id: 47,
      campus_id: 10,
      name: "해남군학습관"
    }, {
      building_id: 48,
      campus_id: 10,
      name: "목포시학습관"
    }]
  }, {
    campus_id: 11,
    name: "제주",
    web_address: null,
    building_rseults: [{
      building_id: 49,
      campus_id: 11,
      name: "제주지역대학"
    }]
  }]

}